/* soapClient.cpp
   Generated by gSOAP 2.8.17r from wsdl.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.17r 2014-01-24 09:13:28 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getLastDumpDate(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getLastDumpDate *ns1__getLastDumpDate, _ns1__getLastDumpDateResponse *ns1__getLastDumpDateResponse)
{	struct __ns1__getLastDumpDate soap_tmp___ns1__getLastDumpDate;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://vigruzki.rkn.gov.ru/services/OperatorRequest/";
	if (soap_action == NULL)
		soap_action = "http://vigruzki.rkn.gov.ru/services/OperatorRequest/getLastDumpDate";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getLastDumpDate.ns1__getLastDumpDate = ns1__getLastDumpDate;
	soap_serializeheader(soap);
	soap_serialize___ns1__getLastDumpDate(soap, &soap_tmp___ns1__getLastDumpDate);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getLastDumpDate(soap, &soap_tmp___ns1__getLastDumpDate, "-ns1:getLastDumpDate", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getLastDumpDate(soap, &soap_tmp___ns1__getLastDumpDate, "-ns1:getLastDumpDate", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getLastDumpDateResponse)
		return soap_closesock(soap);
	ns1__getLastDumpDateResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getLastDumpDateResponse->soap_get(soap, "ns1:getLastDumpDateResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__sendRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__sendRequest *ns1__sendRequest, _ns1__sendRequestResponse *ns1__sendRequestResponse)
{	struct __ns1__sendRequest soap_tmp___ns1__sendRequest;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://vigruzki.rkn.gov.ru/services/OperatorRequest/";
	if (soap_action == NULL)
		soap_action = "http://vigruzki.rkn.gov.ru/services/OperatorRequest/sendRequest";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__sendRequest.ns1__sendRequest = ns1__sendRequest;
	soap_serializeheader(soap);
	soap_serialize___ns1__sendRequest(soap, &soap_tmp___ns1__sendRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__sendRequest(soap, &soap_tmp___ns1__sendRequest, "-ns1:sendRequest", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__sendRequest(soap, &soap_tmp___ns1__sendRequest, "-ns1:sendRequest", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__sendRequestResponse)
		return soap_closesock(soap);
	ns1__sendRequestResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__sendRequestResponse->soap_get(soap, "ns1:sendRequestResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getResult(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getResult *ns1__getResult, _ns1__getResultResponse *ns1__getResultResponse)
{	struct __ns1__getResult soap_tmp___ns1__getResult;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://vigruzki.rkn.gov.ru/services/OperatorRequest/";
	if (soap_action == NULL)
		soap_action = "http://vigruzki.rkn.gov.ru/services/OperatorRequest/getResult";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getResult.ns1__getResult = ns1__getResult;
	soap_serializeheader(soap);
	soap_serialize___ns1__getResult(soap, &soap_tmp___ns1__getResult);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getResult(soap, &soap_tmp___ns1__getResult, "-ns1:getResult", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getResult(soap, &soap_tmp___ns1__getResult, "-ns1:getResult", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getResultResponse)
		return soap_closesock(soap);
	ns1__getResultResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getResultResponse->soap_get(soap, "ns1:getResultResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
